In [1]:
import numpy as np

In [2]:
minha_lista = [1, 2, 3]

In [3]:
minha_lista

[1, 2, 3]

In [4]:
np.array(minha_lista)

array([1, 2, 3])

In [6]:
minha_matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(minha_matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
arr = np.zeros((5, 5))

In [15]:
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
np.linspace(0, 10, 2)

array([ 0., 10.])

In [21]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [30]:
np.round(np.random.rand(5) *100, 0)

array([99., 76., 73.,  2., 94.])

In [24]:
np.random.rand(5, 5) * 100

array([[32.0907152 , 78.75558658, 77.59503546, 27.32717363,  3.09945467],
       [96.40398169, 40.32395954, 61.1878534 , 51.50303272, 26.33119431],
       [75.92928053, 47.14308202, 59.13520916, 18.45242524, 27.01435534],
       [26.36717326, 37.51070098, 39.55007114, 36.83920112, 11.34118289],
       [64.98456082, 52.45180081, 81.52410554, 93.93213382, 62.3473318 ]])

In [26]:
np.random.randn(5, 5, 3)

array([[[-1.57808494, -1.2695412 ,  1.40147577],
        [-0.68709744, -0.23114943,  1.6901516 ],
        [ 1.64308979, -0.83359296, -0.94080189],
        [ 1.09246147,  0.0077352 , -1.10877587],
        [-0.32350247, -0.80901045,  1.16622176]],

       [[-0.14564918, -0.77552858,  0.02559278],
        [-0.68038644,  0.85327964, -0.24672081],
        [ 0.05580946, -0.97478804,  0.22966694],
        [-1.01545403, -0.70165637, -0.4181548 ],
        [-0.61502379, -0.17864384,  0.42182598]],

       [[-0.88308042, -1.34157444,  0.07404618],
        [-0.62959792, -1.44636745, -0.61484561],
        [-1.01569654, -0.45341494, -1.30269523],
        [-1.25406565, -0.31146396, -0.2534098 ],
        [-0.26235948,  0.56563264, -1.24021502]],

       [[-0.5492087 ,  0.16812149,  0.3726908 ],
        [-0.80816261, -0.96673984, -0.6579645 ],
        [ 0.8993385 , -0.32958322, -0.62837159],
        [ 1.22897062, -1.4661733 ,  0.68747301],
        [ 0.55339739,  1.54399822,  0.20428753]],

       [[-0.

In [28]:
np.random.randint(0, 100, 10)

array([13,  5, 39, 28,  2, 55,  2, 24, 86, 57])

In [31]:
arr = np.random.rand(25)

In [32]:
arr

array([0.98428171, 0.49243787, 0.66296624, 0.87420869, 0.34796608,
       0.74641571, 0.79463915, 0.48302938, 0.42073356, 0.7958985 ,
       0.57036409, 0.86574357, 0.59454304, 0.20371355, 0.29298063,
       0.61252815, 0.08522355, 0.28260754, 0.38788127, 0.03304156,
       0.6052824 , 0.29492906, 0.28736508, 0.97311523, 0.53926106])

In [40]:
arr.reshape((5, 5))

array([[0.98428171, 0.49243787, 0.66296624, 0.87420869, 0.34796608],
       [0.74641571, 0.79463915, 0.48302938, 0.42073356, 0.7958985 ],
       [0.57036409, 0.86574357, 0.59454304, 0.20371355, 0.29298063],
       [0.61252815, 0.08522355, 0.28260754, 0.38788127, 0.03304156],
       [0.6052824 , 0.29492906, 0.28736508, 0.97311523, 0.53926106]])

In [34]:
arr

array([0.98428171, 0.49243787, 0.66296624, 0.87420869, 0.34796608,
       0.74641571, 0.79463915, 0.48302938, 0.42073356, 0.7958985 ,
       0.57036409, 0.86574357, 0.59454304, 0.20371355, 0.29298063,
       0.61252815, 0.08522355, 0.28260754, 0.38788127, 0.03304156,
       0.6052824 , 0.29492906, 0.28736508, 0.97311523, 0.53926106])

In [41]:
arr.shape

(25,)

In [43]:
arr.max()

0.9842817092638816

In [44]:
arr.min()

0.033041560208662446

In [45]:
arr.argmax()

0